name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Run hello_world.sh
      run: echo "Oh, how dastardly, this isn't the v1 release..."
      shell: bash
