name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Run hello_world.sh
      run: echo "They just don't make character code tables like they did when I was growing up..."
      shell: bash
